blank_issues_enabled: false
contact_links:
  - name: Discord Community Support
    url: https://discord.com/channels/1186702814341234740/1195760902260142262
    about: If you want to submit and raise anything else, please reach out here
