name: "Question Submission From"
description: Use this template to submit a question to the team 
title: '[Question]:'
labels: ["Question"]

body:
  - type: markdown
    attributes:
      value: "## Welcome! Use this template to submit a question!"
      
  - type: textarea
    id: question
    attributes:
      label: What is the question you want to raise?
      description: Write the quesiton of interest 
      value: "[Your question here]" 
  
  - type: textarea
    id: description
    attributes:
      label: "**Description:**"
      description: Additional context or details related to the question
      value: "[Your text here]"
