name: "Question Submission From"
description: Use this template to submit a question to the team 
title: '[Question]:[Question title]'
labels: ["Question"]

body:

  - type: textarea
    id: question
    attributes:
      label: What is the qesution you want to raise?
      description: Write the quesiton of interest 
      placeholder: Tell us what you see!
      value: "[Your question here]" 
  
  - type: textarea
    id: description
    attributes:
      label: "**Description:**"
      description: Additional context or details related to the question
      value: "[Your text here]"
