name: Question Submission
description: Use this template to submit a question.

title: '[Date]: [Question]'
labels: ["Question"]

body:
  - type: markdown
    id: question
    attributes:
      value: |
        **Question:**
        **Description:** [Additional context or details related to the question]
        **Tags:** [Optional: Tags or keywords to categorize the question]
  
  - type: textarea
    id: question
    attributes:
      label: What is the qesution you want to raise?
      description: Write the quesiton of interest 
      placeholder: Tell us what you see!
      value: "Write your question here"
